"use strict";

const CACHE_PREFIX = "zzpice-assets-";
const CACHE_NAME = CACHE_PREFIX + "v3-8d15cade70d7";
const PREVIEW_CACHE = CACHE_PREFIX + "previews-v1";
const ICON_CACHE = CACHE_PREFIX + "icons-v1";
const base = new URL("./", self.location.href);
// Generated by update_catalog.py: one complete, verified application version.
const SHELL_HASHES = {
  "index.html": "3957f496cfd26dae1b5ef07927fade86c27532800a402c4ff5d635198d748200",
  "catalog.json": "be4308cff947153cfbbbd473159065cd984d7f8f6563ca5818641d133e020423",
  "app/site.js?v=1015e75f0b": "1015e75f0bb7eb50ec9b9f3fc05ce5183814a44f2d7c22c16289500b2a219a72",
  "app/site.css?v=210c82b476": "210c82b4764f6fd92fb117a633b1fbe977100268f807bae5873f522374a961b4",
  "app/theme.css?v=ad678d78fd": "ad678d78fdd945df4cfde6f8cc48f1f01f6af3522f476651e436a05f3bae828d",
  "app/catalog.js?v=2f72d84160": "2f72d84160edd1ca0f7ae457c01eb389b5b60d6b37ebfe0cf95854b9dcd2315d",
  "app/actresses.js?v=4619ad5278": "4619ad52782b7419e7fc2b0c6708f2bf1d124cb8363cfab5c325ca045ac3b041",
  "app/manifest.webmanifest": "14e9d0e29ecdf9951c3fa590d712dbce65a64376aca04ed736bb5bfcf73177a5",
  "app/icon.svg": "9eea0b58ac270eba0edb38d88d5eb24db3b10093c78da04dc10fd35d6a09645a",
  "app/icon-180.png": "cccf80fbb2ea204fd24a9fb5824fa1ecf17549654e31ce44466bd728ab3d08cd",
  "app/icon-192.png": "81d50354c8d554caf5630b193c4baa296998f09d6f4fccc12f0ff22e1ecb5721",
  "app/icon-512.png": "fc575c7217c06be0901a28ab93798f2a394e17345317524dc2211d2d46c7a2c6"
};

async function contentHash(data, gitBlob = false) {
  let bytes = new Uint8Array(data);
  if (gitBlob) {
    const header = new TextEncoder().encode("blob " + bytes.length + "\0");
    const blob = new Uint8Array(header.length + bytes.length);
    blob.set(header); blob.set(bytes,header.length); bytes = blob;
  }
  const hash = await crypto.subtle.digest(gitBlob ? "SHA-1" : "SHA-256",bytes);
  return [...new Uint8Array(hash)].map(value => value.toString(16).padStart(2,"0")).join("");
}

async function verifiedResponse(request, expected, {gitBlob = false, timeoutMs = 8000} = {}) {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(),timeoutMs);
  try {
    const response = await fetch(request,{cache:"no-cache",signal:controller.signal});
    if (!response.ok) throw new Error("HTTP " + response.status);
    const data = await response.clone().arrayBuffer();
    if (await contentHash(data,gitBlob) !== expected) throw new Error("Resource version mismatch: " + request.url);
    return response;
  } finally { clearTimeout(timeout); }
}

async function trimCache(cache, limit) {
  const keys = await cache.keys();
  await Promise.all(keys.slice(0,Math.max(0,keys.length - limit)).map(key => cache.delete(key)));
}

self.addEventListener("install", event => event.waitUntil((async () => {
  const paths = Object.keys(SHELL_HASHES);
  // Fetch and verify every required file before publishing this cache generation.
  const responses = await Promise.all(paths.map(path => verifiedResponse(new Request(new URL(path,base)),SHELL_HASHES[path])));
  try {
    const cache = await caches.open(CACHE_NAME);
    await Promise.all(paths.map((path,index) => cache.put(new URL(path,base).href,responses[index])));
  } catch (error) { await caches.delete(CACHE_NAME); throw error; }
  const catalog = await (await cachedCatalog()).json();
  const priority = {wallpaper:0,avatar:1,"bank-card":2,other:3};
  // Never prefetch the unlisted collection, even when other previews are sparse.
  const thumbnails = catalog.assets.filter(file => file.kind !== "actress" && file.thumbnail?.startsWith("app/previews/"))
    .sort((a,b) => (priority[a.kind] ?? 3) - (priority[b.kind] ?? 3)).slice(0,24);
  // Optional previews must not leave a complete shell waiting on a stalled network.
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(),8000);
  try {
    await Promise.allSettled(thumbnails.map(file => thumbnailResponse(new Request(new URL(file.thumbnail,base),{signal:controller.signal}))));
  } finally { clearTimeout(timeout); }
})()));

async function cachedCatalog() {
  return (await caches.open(CACHE_NAME)).match(new URL("catalog.json",base).href);
}

self.addEventListener("activate", event => event.waitUntil((async () => {
  const catalog = await (await cachedCatalog()).json();
  const thumbnails = new Set(catalog.assets.filter(file => file.thumbnail).map(file => new URL(file.thumbnail,base).href));
  const icons = new Set(catalog.assets.filter(file => file.kind === "icon").map(file => new URL(file.path + "?v=" + file.sha,base).href));
  const previews = await caches.open(PREVIEW_CACHE);
  const keys = await caches.keys();
  for (const key of keys.filter(key => key.startsWith(CACHE_PREFIX) && ![CACHE_NAME,PREVIEW_CACHE,ICON_CACHE].includes(key))) {
    // Keep still-current previews from the previous worker before deleting its shell.
    const old = await caches.open(key);
    for (const request of await old.keys()) {
      if (thumbnails.has(request.url) && !(await previews.match(request))) {
        await previews.put(request,await old.match(request)).catch(() => {});
      }
    }
    await caches.delete(key);
  }
  for (const [name,allowed,limit] of [[PREVIEW_CACHE,thumbnails,32],[ICON_CACHE,icons,64]]) {
    const cache = await caches.open(name);
    await Promise.all((await cache.keys()).filter(request => !allowed.has(request.url)).map(request => cache.delete(request)));
    await trimCache(cache,limit);
  }
  await self.clients.claim();
})()));

function shellPath(request) {
  const url = new URL(request.url);
  const path = url.pathname.slice(base.pathname.length);
  if (path === "" || path === "index.html") return "index.html";
  if (Object.keys(SHELL_HASHES).some(key => key.startsWith(path + "?v="))) {
    return url.search ? path + url.search : Object.keys(SHELL_HASHES).find(key => key.startsWith(path + "?v="));
  }
  return path;
}

async function shellResponse(request) {
  const path = shellPath(request);
  if (!SHELL_HASHES[path]) throw new Error("Application resource version unavailable");
  const key = new URL(path,base).href;
  const cache = await caches.open(CACHE_NAME);
  const cached = await cache.match(key);
  if (cached) return cached;
  const response = await verifiedResponse(new Request(key),SHELL_HASHES[path]);
  await cache.put(key,response.clone()).catch(() => {});
  return response;
}

async function thumbnailResponse(request) {
  const cache = await caches.open(PREVIEW_CACHE);
  const cached = await cache.match(request);
  if (cached) return cached;
  const response = await fetch(request);
  if (response.ok) {
    await cache.put(request,response.clone()).catch(() => {});
    await trimCache(cache,32);
  }
  return response;
}

async function iconResponse(request) {
  const url = new URL(request.url);
  const sha = url.searchParams.get("v");
  url.search = "?v=" + sha;
  const cache = await caches.open(ICON_CACHE);
  const cached = await cache.match(url.href);
  if (cached) return cached;
  // Image requests can queue behind other visible images on a cold connection.
  // Keep shell recovery short while allowing this independent cache more time.
  const response = await verifiedResponse(new Request(url.href),sha,{gitBlob:true,timeoutMs:30000});
  await cache.put(url.href,response.clone()).catch(() => {});
  await trimCache(cache,64);
  return response;
}

self.addEventListener("fetch", event => {
  const request = event.request;
  const url = new URL(request.url);
  if (request.method !== "GET" || url.origin !== base.origin || !url.pathname.startsWith(base.pathname)) return;
  const path = url.pathname.slice(base.pathname.length);
  if (path.startsWith("app/previews/")) event.respondWith(thumbnailResponse(request));
  else if (path.startsWith("icons/") && /\.png$/.test(path) && /^[a-f0-9]{40}$/.test(url.searchParams.get("v") || "")) event.respondWith(iconResponse(request));
  else if (path === "" || Object.keys(SHELL_HASHES).some(key => key.split("?")[0] === path)) event.respondWith(shellResponse(request));
  // Canonical full-size download URLs retain normal browser behavior.
});
