"use strict";

const CACHE_PREFIX = "zzpice-assets-";
const CACHE_NAME = CACHE_PREFIX + "v3-73f19882ae87";
const PREVIEW_CACHE = CACHE_PREFIX + "previews-v1";
const ICON_CACHE = CACHE_PREFIX + "icons-v1";
const base = new URL("./", self.location.href);
// Generated by update_catalog.py: one complete, verified application version.
const SHELL_HASHES = {
  "index.html": "ad8ab070680caacfffa643af6bce2612e28a17001d4a3602da2a8cd7bbe1f836",
  "catalog.json": "fc7bcf74deca09c87f22de0fa59cca45a72f2edd4c710b1f8623836ee46a3ad2",
  "app/site.js?v=149d446d3c": "149d446d3ca0d1deaef1a17113d08f3dc45d2f2fd55782c7996b7233a4d32e0d",
  "app/site.css?v=183c4ec47c": "183c4ec47cac8d11a57ae1acace0364557be0ee44126647fd1d314f30a251105",
  "app/manifest.webmanifest": "7a16a6a6cc4fa1a65676c94d8407b385ab5d823579cce8d2f062cfc6a26613b6",
  "app/icon.svg": "c8df6bbe05021afe1b5e66004a053dbf2606be263dffe9488b682c74e271483f",
  "app/icon-180.png": "04530a5f1b34338c9d3cdfb55e7d8f27c183376be673649b17f91b3c4aa03d77",
  "app/icon-192.png": "f79fc18edff25df7c349392dec9df81b32f0afed88594363a44acaadd02fa50f",
  "app/icon-512.png": "b0de2e955d967e6e2612b9229bad04000cc0290f43da27ef576bd934e2bf053e"
};

async function contentHash(data, gitBlob = false) {
  let bytes = new Uint8Array(data);
  if (gitBlob) {
    const header = new TextEncoder().encode("blob " + bytes.length + "\0");
    const blob = new Uint8Array(header.length + bytes.length);
    blob.set(header); blob.set(bytes,header.length); bytes = blob;
  }
  const hash = await crypto.subtle.digest(gitBlob ? "SHA-1" : "SHA-256",bytes);
  return [...new Uint8Array(hash)].map(value => value.toString(16).padStart(2,"0")).join("");
}

async function verifiedResponse(request, expected, gitBlob = false) {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(),8000);
  try {
    const response = await fetch(request,{cache:"no-cache",signal:controller.signal});
    if (!response.ok) throw new Error("HTTP " + response.status);
    const data = await response.clone().arrayBuffer();
    if (await contentHash(data,gitBlob) !== expected) throw new Error("Resource version mismatch: " + request.url);
    return response;
  } finally { clearTimeout(timeout); }
}

async function trimCache(cache, limit) {
  const keys = await cache.keys();
  await Promise.all(keys.slice(0,Math.max(0,keys.length - limit)).map(key => cache.delete(key)));
}

self.addEventListener("install", event => event.waitUntil((async () => {
  const paths = Object.keys(SHELL_HASHES);
  // Fetch and verify every required file before publishing this cache generation.
  const responses = await Promise.all(paths.map(path => verifiedResponse(new Request(new URL(path,base)),SHELL_HASHES[path])));
  try {
    const cache = await caches.open(CACHE_NAME);
    await Promise.all(paths.map((path,index) => cache.put(new URL(path,base).href,responses[index])));
  } catch (error) { await caches.delete(CACHE_NAME); throw error; }
  const catalog = await (await cachedCatalog()).json();
  const priority = {wallpaper:0,avatar:1,"bank-card":2,other:3};
  const thumbnails = catalog.assets.filter(file => file.thumbnail?.startsWith("app/previews/"))
    .sort((a,b) => (priority[a.kind] ?? 3) - (priority[b.kind] ?? 3)).slice(0,24);
  await Promise.allSettled(thumbnails.map(file => thumbnailResponse(new Request(new URL(file.thumbnail,base)))));
})()));

async function cachedCatalog() {
  return (await caches.open(CACHE_NAME)).match(new URL("catalog.json",base).href);
}

self.addEventListener("activate", event => event.waitUntil((async () => {
  const catalog = await (await cachedCatalog()).json();
  const thumbnails = new Set(catalog.assets.filter(file => file.thumbnail).map(file => new URL(file.thumbnail,base).href));
  const icons = new Set(catalog.assets.filter(file => file.kind === "icon").map(file => new URL(file.path + "?v=" + file.sha,base).href));
  const previews = await caches.open(PREVIEW_CACHE);
  const keys = await caches.keys();
  for (const key of keys.filter(key => key.startsWith(CACHE_PREFIX) && ![CACHE_NAME,PREVIEW_CACHE,ICON_CACHE].includes(key))) {
    // Keep still-current previews from the previous worker before deleting its shell.
    const old = await caches.open(key);
    for (const request of await old.keys()) {
      if (thumbnails.has(request.url) && !(await previews.match(request))) {
        await previews.put(request,await old.match(request)).catch(() => {});
      }
    }
    await caches.delete(key);
  }
  for (const [name,allowed,limit] of [[PREVIEW_CACHE,thumbnails,32],[ICON_CACHE,icons,64]]) {
    const cache = await caches.open(name);
    await Promise.all((await cache.keys()).filter(request => !allowed.has(request.url)).map(request => cache.delete(request)));
    await trimCache(cache,limit);
  }
  await self.clients.claim();
})()));

function shellPath(request) {
  const url = new URL(request.url);
  const path = url.pathname.slice(base.pathname.length);
  if (path === "" || path === "index.html") return "index.html";
  if (["app/site.js","app/site.css"].includes(path)) {
    return url.search ? path + url.search : Object.keys(SHELL_HASHES).find(key => key.startsWith(path + "?v="));
  }
  return path;
}

async function shellResponse(request) {
  const path = shellPath(request);
  if (!SHELL_HASHES[path]) throw new Error("Application resource version unavailable");
  const key = new URL(path,base).href;
  const cache = await caches.open(CACHE_NAME);
  const cached = await cache.match(key);
  if (cached) return cached;
  const response = await verifiedResponse(new Request(key),SHELL_HASHES[path]);
  await cache.put(key,response.clone()).catch(() => {});
  return response;
}

async function thumbnailResponse(request) {
  const cache = await caches.open(PREVIEW_CACHE);
  const cached = await cache.match(request);
  if (cached) return cached;
  const response = await fetch(request);
  if (response.ok) {
    await cache.put(request,response.clone()).catch(() => {});
    await trimCache(cache,32);
  }
  return response;
}

async function iconResponse(request) {
  const url = new URL(request.url);
  const sha = url.searchParams.get("v");
  url.search = "?v=" + sha;
  const cache = await caches.open(ICON_CACHE);
  const cached = await cache.match(url.href);
  if (cached) return cached;
  const response = await verifiedResponse(new Request(url.href),sha,true);
  await cache.put(url.href,response.clone()).catch(() => {});
  await trimCache(cache,64);
  return response;
}

self.addEventListener("fetch", event => {
  const request = event.request;
  const url = new URL(request.url);
  if (request.method !== "GET" || url.origin !== base.origin || !url.pathname.startsWith(base.pathname)) return;
  const path = url.pathname.slice(base.pathname.length);
  if (path.startsWith("app/previews/")) event.respondWith(thumbnailResponse(request));
  else if (path.startsWith("icons/") && /\.png$/.test(path) && /^[a-f0-9]{40}$/.test(url.searchParams.get("v") || "")) event.respondWith(iconResponse(request));
  else if (path === "" || path === "index.html" || path === "catalog.json" || path.startsWith("app/")) event.respondWith(shellResponse(request));
  // Canonical full-size download URLs retain normal browser behavior.
});
